packages:
  - 'backend'
  - 'frontend'

catalog:
  typescript: '7.0.2'
  '@types/bun': '^1.3.14'
  valibot: '^1.4.2'
  oxfmt: '^0.59.0'

allowBuilds:
  esbuild: true
  lefthook: true

minimumReleaseAgeExclude:
  - '@enshou/core'
  - '@enshou/di'
  - '@enshou/openapi'
  - '@enshou/valibot'
  - '@kanjou/config'
  - '@kanjou/react'
  - '@kanjou/vite'
  - '@enshou/cron'
